In [3]:
import pandas as pd

In [5]:
import numpy as np

In [63]:
df = pd.read_csv("C:/Users/Dell/Downloads/Indian_Cricket_Team_Dataset.csv")
df

Player Name  Age  Matches Played  Batting Average  Strike Rate
0       Player_1   26             456            27.70       188.21
1       Player_2   23             154            24.61       139.34
2       Player_3   32             210            36.87       182.79
3       Player_4   34             426            51.81       178.77
4       Player_5   30             221            49.80       162.44
..           ...  ...             ...              ...          ...
995   Player_996   24             279            23.46       187.80
996   Player_997   28             344            29.47       160.55
997   Player_998   23             126            49.30       124.71
998   Player_999   35              16            41.93       135.59
999  Player_1000   30             146            25.12       108.39

[1000 rows x 5 columns]

In [13]:
numpy_array = excel_data.to_numpy()
print(numpy_array)

[['Player_1' 26 456 27.7 188.21]
 ['Player_2' 23 154 24.61 139.34]
 ['Player_3' 32 210 36.87 182.79]
 ...
 ['Player_998' 23 126 49.3 124.71]
 ['Player_999' 35 16 41.93 135.59]
 ['Player_1000' 30 146 25.12 108.39]]


## Query 1: Convert 'Age' column to a NumPy array.

In [46]:
ages_array = df['Age'].to_numpy()
print(ages_array[:1000])

[26 23 32 34 30 27 32 24 26 29 22 26 30 30 27 24 23 27 27 22 25 24 21 27
 31 33 25 21 35 31 24 20 31 29 25 32 31 28 20 30 30 34 29 35 31 31 35 34
 33 33 34 33 22 31 26 23 35 28 22 24 22 26 24 28 26 21 23 28 31 33 21 29
 28 29 24 21 23 31 34 31 26 31 32 27 34 22 33 20 23 21 27 23 21 33 25 25
 29 23 25 32 34 21 29 31 21 29 33 23 33 34 35 34 27 33 26 31 28 33 27 24
 35 32 21 34 24 27 29 28 31 31 31 32 28 32 34 32 20 28 26 28 27 20 31 27
 27 34 30 22 20 27 22 22 20 30 24 29 26 29 28 31 26 28 27 31 21 20 35 26
 26 33 27 24 22 31 27 25 30 22 20 22 24 34 33 22 20 24 29 26 34 33 26 30
 28 34 34 29 29 31 32 22 34 35 26 20 23 32 35 23 33 24 26 26 32 34 30 32
 23 32 35 26 30 22 25 31 21 29 32 33 28 24 25 31 31 31 31 23 33 33 30 35
 29 26 31 28 26 33 20 20 28 30 33 28 23 32 28 22 26 25 27 30 28 33 24 20
 22 29 31 27 34 30 25 35 35 27 28 23 20 33 20 29 23 31 33 26 21 22 20 24
 20 27 20 30 20 21 21 31 25 26 24 35 20 20 22 33 21 24 31 29 35 25 35 26
 23 26 30 27 30 20 34 25 27 24 23 21 25 25 30 34 35

## Query 2: Find the average age of players.

In [67]:
x= np.array(df["Age"].mean())
print(x)

27.57


## Query 3: Find the oldest and youngest player age. 

In [71]:
max_age = np.array(df['Age'].max())
print(max_age)
min_age = np.array(df['Age'].min())
print(min_age)

35
20


## Query 4: Count the total number of players above 30 years old.

In [73]:
count = np.array((df['Age']>30)).sum()
count

336

## Query 5: Find the median batting average. 

In [77]:
median = np.array(df['Batting Average'].median())
print(median)

40.135


## Query 6: Find the standard deviation of strike rates.## 

In [81]:
std  = np.array(df['Strike Rate'].std())
print(std)

29.122759125573694


## Query 7: Find the 90th percentile of batting average. 

In [83]:
percentile_90 = np.percentile(batting_avg, 90)
print(round(percentile_90, 2))

55.32


## Query 8: Find the number of players with strike rate above 150.

In [86]:
high_strike = np.sum(strike_rate > 150)
print(high_strike)

513


## Query 9: Reshape the first 20 batting averages into a 4x5 matrix. 

In [89]:
reshaped_matrix = batting_avg[:20].reshape(4, 5)
print(reshaped_matrix)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


## Query 10: Compute row-wise sum of reshaped matrix.

In [92]:
row_sums = np.sum(reshaped_matrix, axis=1)
print(row_sums)

[190.79 193.1  212.87 210.42]


## Query 11: Compute column-wise mean of reshaped matrix.

In [117]:
col_means = np.mean(reshaped_matrix, axis=0)
print(col_means)

[30.5325 35.3575 39.9775 51.2875 44.64  ]


## Query 12: Transpose the reshaped matrix. 

In [98]:
transposed = reshaped_matrix.T
print(transposed)

[[27.7  22.2  34.59 37.64]
 [24.61 38.21 42.43 36.18]
 [36.87 40.9  39.24 42.9 ]
 [51.81 45.78 55.4  52.16]
 [49.8  46.01 41.21 41.54]]


## Query 13: Find the variance of batting average. 

In [111]:
variance = np.array(df['Batting Average'].var())
print(variance)

131.6715008167167


## Query 14: Stack age and matches played horizontally.

In [109]:
n = np.array(df['Age'])
n1 = np.array(df['Matches Played'])
stacked = np.stack((n,n1))
print(stacked)

[[ 26  23  32 ...  23  35  30]
 [456 154 210 ... 126  16 146]]


## Query 15: Split the batting average array into 5 equal parts.

In [107]:
split_arrays = np.array_split(batting_avg, 5)
print(split_arrays[0][:5])

[27.7  24.61 36.87 51.81 49.8 ]
